### ISSUE TITLE
better font?

### ISSUE THREAD

**Issue by tomByrer** [antijingoist/opendyslexic-chrome#6] opened 2016-03-19 22:45 UTC
> determined that reading performance was best with sans serif, monospaced, and roman fonts used in the study.... OpenDyslexic font did not enhance text readability or reading speed. The study participants strongly preferred Verdana or Helvetica over the OpenDyslexic alternative.

http://blog.dyslexia.com/good-fonts-for-dyslexia-an-experimental-study/

Perhaps it would be better to override using one of these other fonts?
##

**Comment by RobertJGabriel** [comment] 2016-03-19 22:50
Thanks , I'm not sure about completely replacing it but maybe a dropdown with different choices of fonts, cause it is the official extension for the opendyslexic font :) What do you think @antijingoist  ?

**Comment by antijingoist** [comment] 2016-04-26 01:53
When OpenDyslexic was released, it was intended to change with feedback, in order to continually make it better.

In 2013, OpenDyslexic looked different than it does now, and had worse kerning (or, at least bad enough that commenters on Gizmodo wished me dead).

Below, you can see the 2013 OpenDyslexic embedded in the PDF of the study, current OpenDyslexic, and OpenDyslexic 3. 
![2016-04-25_21-45-07](https://cloud.githubusercontent.com/assets/663100/14804229/6af77920-0b2f-11e6-9c0b-67972a4ba839.png)

That said, while I'm not entirely opposed to adding additional typefaces to a dropdown, it seems out of scope for the plugin, and marching into territory that has been frequently done before. I thought of the idea of offering a comparison type mode, but that seems to be served with the on/off switch that @RobertJGabriel has added.

**Closed** 2018-03-16 04:04 UTC
